# This will be set by the GitHub action to the folder containing this component.
ARG FOLDER=/app

FROM ghost:alpine

COPY --chown=1000:1000 . /app
COPY --chown=1000:1000 ./.diploi/diploi-storage-adapter.js /var/lib/ghost/versions/$GHOST_VERSION/core/server/adapters/storage/

ENV NODE_ENV=development
ENV paths__contentPath=${FOLDER}

USER 1000:1000